stages:
    - test
  
.test-opensource: &test-opensource
  stage: test
  tags:
    - docker
  image: centos:7
  before_script:
    - curl -s https://packagecloud.io/install/repositories/tarantool/$TARANTOOL_REPO/script.rpm.sh | bash
    - curl -sL https://rpm.nodesource.com/setup_8.x | bash
    - yum -y install git gcc cmake tarantool tarantool-devel unzip nodejs
    - tarantool -V
    - tarantoolctl rocks install luatest 0.5.0
  script:
    - tarantoolctl rocks make
    - .rocks/bin/luatest -v

test-opensource-2.x:
  <<: *test-opensource
  variables:
    TARANTOOL_REPO: "2_4"
