name: Publish

on:
  push:
    branches: [master]
    tags: ['*']

env:
  # Skip building cartridge WebUI
  CMAKE_DUMMY_WEBUI: true

jobs:
  publish-scm-1:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: tarantool/rocks.tarantool.org/github-action@master
        with:
          auth: ${{ secrets.ROCKS_AUTH }}
          files: cartridge-extensions-scm-1.rockspec

  publish-tag:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: tarantool/setup-tarantool@v2
        with:
          tarantool-version: '2.8'

      # Make a release
      - run: echo TAG=${GITHUB_REF##*/} >> $GITHUB_ENV
      - run: tarantoolctl rocks new_version --tag ${{ env.TAG }}
      - run: sed -i '/branch = "master"/d' cartridge-extensions-${{ env.TAG }}-1.rockspec
      - run: tarantoolctl rocks install cartridge-extensions-${{ env.TAG }}-1.rockspec
      - run: tarantoolctl rocks pack cartridge-extensions ${{ env.TAG }}

      - uses: tarantool/rocks.tarantool.org/github-action@master
        with:
          auth: ${{ secrets.ROCKS_AUTH }}
          files: |
            cartridge-extensions-${{ env.TAG }}-1.rockspec
            cartridge-extensions-${{ env.TAG }}-1.all.rock
